import MenuBar from "./_components/MenuBar"
import DataProvider from "./_components/DataProvider"
export const metadata = {
  title: 'Simple app',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <DataProvider>
              <h1>Simple app 3.0</h1>
              <hr />  
              <MenuBar />
              <hr />
              {children}             
          </DataProvider>
      </body>
    </html>
  )
}
